# Generated by Django 5.1.6 on 2025-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_discount_tax_order_discounts_order_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='orders', to='payments.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='orders', to='payments.tax'),
        ),
    ]
