# Generated by Django 5.1.6 on 2025-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_order_discounts_alter_order_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
