# Generated by Django 5.1.6 on 2025-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_stripe_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='stripe_tax_rate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
