# Generated by Django 5.1.6 on 2025-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_tax_stripe_tax_rate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
